services:
  collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4318:4318" # HTTP
  jaeger:
    image: jaegertracing/all-in-one:1.49
    environment:
      SPAN_STORAGE_TYPE: badger
      BADGER_EPHEMERAL: false
      BADGER_DIRECTORY_VALUE: /badger/data
      BADGER_DIRECTORY_KEY: /badger/key
    volumes:
      - badger:/badger
    ports:
      - "16686:16686" # UI
volumes:
  badger:
